apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: token-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: karchit8cture-user-sa