name: karchit8cture CI workflow 
on:
  pull_request:
    branches:
    - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v2

      - name: Install needed dependencies based on requirements.txt file 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: playground
          config: manifests/kind.yaml

      - name: Run a bootstrap script to install all karchit8cture depedencies 
        run: no | ./bootstrap.sh

      - name: Run karchit8cture and print results 
        run: |
          cd karchit8cture
          python3 karchit8cture.py
